DROP TABLE IF EXISTS cart;
CREATE TABLE cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id BIGINT,
  CONSTRAINT pk_cart PRIMARY KEY (id)
);

DROP TABLE IF EXISTS cart_items;
CREATE TABLE cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  quantity INTEGER,
  product_id INTEGER,
  cart_entity_id BIGINT,
  CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

ALTER TABLE cart_items DROP CONSTRAINT IF EXISTS fk_cart_items_on_cart_entity;
ALTER TABLE cart_items ADD CONSTRAINT fk_cart_items_on_cart_entity FOREIGN KEY (cart_entity_id) REFERENCES cart (id);
